DROP TABLE "AspNetRoles" CASCADE CONSTRAINTS;
DROP TABLE "AspNetUserClaims";
DROP TABLE "AspNetUserLogins";
DROP TABLE "AspNetUserRoles";
DROP TABLE "AspNetUsers";
DROP TABLE "Requesters";
DROP TABLE "CasePapers";
DROP TABLE "SearchFields";
DROP TABLE "Histories";
DROP SEQUENCE "SQ_AspNetUserClaims";
